server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:space/jachen/gmall/product/mapper/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://jachen.com:3308/gmall_product
  redis:
    host: jachen.com
    password:
    database: 0
    port: 6379
  zipkin:
    base-url: http://jachen.com:9411
  rabbitmq:
    host: jachen.com
    port: 5672
    username: guest
    password: guest
