spring:
  application:
    name: service-product
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: jachen.com:8848
  devtools:
    livereload:
      enabled: false  # remove Unable to start LiveReload server